<a href="https://colab.research.google.com/github/RadoslawKieronski/BashScripts/blob/main/NumPy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# GENEROWANIE LICZB PSEUDOLOSOWYCH
import numpy as np

In [ ]:
# wygenerowanie liczb za pomocą modułu 'random'

In [ ]:
# wygenerowanie liczb za pomocą funkcji 'randn' rozkładu normalnego
np.random.randn()

-1.0531792314479151

In [ ]:
# Zwróci tablicę 10-ciu losowo wygenerowanych elementów z rozkładu normalnego, standardowego. Czyli o średniej 0 i odchyleniu standardowym 1.
np.random.randn(10)

array([-0.09354131, -1.23037914, -0.95573714, -1.35385098, -0.46294662,
       -1.36197753,  0.48816221, -0.04141145, -0.41711536, -0.04974967])

In [ ]:
# tab 10 wier, 4 kol
np.random.randn(10, 4)

array([[-0.52897896, -0.14122891,  2.85506354,  1.53046193],
       [ 0.71854953, -0.36312815, -0.45611016, -0.31257057],
       [-0.52509529, -0.2122664 ,  1.68498512, -0.85855468],
       [ 0.30364567, -0.10802345,  1.60823108, -0.48100553],
       [ 0.66130302, -1.03536623, -0.91416652, -0.30808941],
       [ 0.36501894,  0.09655396,  1.15453133,  1.2155702 ],
       [-0.21370129,  0.21549387,  0.51259949, -1.03577615],
       [-0.44528117, -0.06621294,  1.06774795, -2.36171668],
       [ 0.49564627,  0.88729126,  0.42890503, -0.63614094],
       [-0.4391224 , -1.11709963,  0.66618059,  0.0091208 ]])

In [ ]:
# Funkcja 'rand' zwróci wartość z przedziału 0 i 1
np.random.rand()

0.5664570098585986

In [ ]:
np.random.rand(10)

array([0.70564778, 0.36831739, 0.88002785, 0.01594248, 0.7569134 ,
       0.58622063, 0.29908624, 0.99559198, 0.88666334, 0.85051323])

In [ ]:
np.random.rand(10, 2)

array([[3.36078254e-01, 7.99648106e-01],
       [4.79681903e-01, 7.91232304e-04],
       [7.84574117e-01, 6.71806717e-01],
       [3.07417710e-01, 7.32024896e-02],
       [3.26138415e-01, 1.60560091e-01],
       [2.08666207e-02, 7.32332565e-03],
       [8.90083921e-01, 2.20209475e-01],
       [7.56729266e-01, 8.23039425e-01],
       [9.04783282e-01, 1.33209914e-01],
       [8.46706591e-01, 1.27936787e-01]])

In [ ]:
# zwróci liczbę z przedziału 0-10
np.random.randint(10)

1

In [ ]:
# losowa liczba z przedziału 10-101
np.random.randint(low=10, high=101)

79

In [ ]:
# wygeneruje 4 losowe liczby z przedziału 10-101
np.random.randint(low=10, high=101, size=4)

array([35, 32, 42, 34])

In [ ]:
# metoda 'choice' zwróci losowy element z podanej listy
np.random.choice([1, 2, 3, 5])

2

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# metoda 'shuffle' przetasuje tablice
np.random.shuffle(data)
data

array([1, 2, 3, 5, 0, 9, 7, 4, 8, 6])